language: rust

rust:
    - stable
    - beta
    - nightly

cache: cargo

env:
    - RUST_TEST_THREADS=1

sudo: false

script:
    - cargo build -v --all-targets
    - cargo test -v --no-fail-fast
    - cargo test -v --no-fail-fast --features u2i
    - cd serde-tests && cargo test -v --no-fail-fast
